P335_BackEnd/P335_BackEnd/Entities/ContactInfo.cs
namespace P335_BackEnd.Entities
{
    public class ContactInfo
    {
        public int Id{ get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
    }
}

P335_BackEnd/P335_BackEnd/Areas/Admin/Controllers/ContactInfoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using P335_BackEnd.Areas.Admin.Models;
using P335_BackEnd.Data;

namespace P335_BackEnd.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ContactInfoController : Controller
    {
        private readonly AppDbContext _dbContext;

        public ContactInfoController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var contactInfo = _dbContext.ContactInfo.FirstOrDefault();
            if (contactInfo == null) return NotFound();

            var model = new ContactInfoIndexVM
            {
                Email = contactInfo.Email,
                PhoneNumber = contactInfo.PhoneNumber
            };
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Index(ContactInfoIndexVM model)
        {
            var contactInfo = _dbContext.ContactInfo.FirstOrDefault();
            if (contactInfo == null) return NotFound();

            contactInfo.Email = model.Email;
            contactInfo.PhoneNumber = model.PhoneNumber;

            _dbContext.ContactInfo.Update(contactInfo);
            _dbContext.SaveChanges();

            return View(model);
        }
    }
}

P335_BackEnd/P335_BackEnd/Areas/Admin/Views/ContactInfo/Index.cshtml
@model ContactInfoIndexVM
@{
    bool disableInput = !User.IsInRole("Admin");
}

<h1>Contact Info</h1>

<form asp-controller="ContactInfo" asp-action="Index" method="post">
    <div class="form-group mt-5">
        <label for="email1">Email address</label>
        <input disabled="@disableInput" asp-for="Email" class="form-control" id="email1">
    </div>
    <div class="form-group mt-1">
        <label for="number2">Phone Number</label>
        <input disabled="@disableInput" asp-for="PhoneNumber" class="form-control" id="number2">
    </div>
    <button disabled="@disableInput" type="submit" class="btn btn-warning mt-3">Update</button>
</form>